name: scheduled-demo-api

on:
  schedule: "*/5 * * * *" # every 5 minutes

jobs:
  build-and-test:
    runs_on: vm
    steps:
      - name: Checkout
        uses: checkout

      - name: Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -v -count=1 ./...

      - name: Vet
        run: go vet ./...
